
package com.wisdom.mtwebservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MTWebServiceIFService", targetNamespace = "http://mtwebservice.wisdom.com/", wsdlLocation = "http://100.11.1.27:8888/mtservice?wsdl")
public class MTWebServiceIFService
    extends Service
{

    private final static URL MTWEBSERVICEIFSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://100.11.1.27:8888/mtservice?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        MTWEBSERVICEIFSERVICE_WSDL_LOCATION = url;
    }

    public MTWebServiceIFService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MTWebServiceIFService() {
        super(MTWEBSERVICEIFSERVICE_WSDL_LOCATION, new QName("http://mtwebservice.wisdom.com/", "MTWebServiceIFService"));
    }

    /**
     * 
     * @return
     *     returns MTWebServiceIF
     */
    @WebEndpoint(name = "MTWebServiceIFPort")
    public MTWebServiceIF getMTWebServiceIFPort() {
        return (MTWebServiceIF)super.getPort(new QName("http://mtwebservice.wisdom.com/", "MTWebServiceIFPort"), MTWebServiceIF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MTWebServiceIF
     */
    @WebEndpoint(name = "MTWebServiceIFPort")
    public MTWebServiceIF getMTWebServiceIFPort(WebServiceFeature... features) {
        return (MTWebServiceIF)super.getPort(new QName("http://mtwebservice.wisdom.com/", "MTWebServiceIFPort"), MTWebServiceIF.class, features);
    }

}
